### ISSUE TITLE
When a user signin it will create over 50 SystemUserSession records in the database.

### ISSUE THREAD

**Issue by andwah** [Starcounter/SignIn#155]
### Steps to reproduce
Start with an empty database.
1. Start: UserAdmin
2. Start: SignIn
3. Navigate to http://localhost:8080/useradmin
4. Add a password to the admin user
5. Navigate to http://localhost:8080/SignIn
6. Signin with admin + password
7. do the following query in Starcounter Admin
     `select  * from signin.systemusersession`
### Expected result
   I expected only one systemUserSession record
### Actual result
More then 50 systemUserSession records in database
##### Starcounter version 
Starcounter-Custom-2.4.990.9 (Jan 17, 2018 4:28:30 PM)
##### Involved apps' version

Signin (refactor-without-simplified)
UserAdmin (refactor-without-simplified)

**Comment by warpech** [comment]
Isn't this fixed in https://github.com/Starcounter/SignIn/commit/76cc0d6f074592122dad18299b9488942737fc69?

Same problem was tracked in https://github.com/Starcounter/AppsTeam/issues/264

Can this be closed @habib535 ?

**Comment by habib535** [comment]
Closing as fixed.
