### ISSUE TITLE
Refresh during a UserSession will create a new UserSession, over and over and over

### ISSUE THREAD

**Issue by wanderlust-ginge** [Starcounter/SignIn#164]
### Steps to reproduce
Start with a clean database
Run Signin and UserAdmin together
Create a User in UserAdmin
Sign in with that User using SignIn
Check SignIn.SystemUserSession entries in Database
Refresh SignIn Page (or another open page associated with User)
Check Database again and see a new session as well as the old session
Repeat

### Expected result
There should only be one UserSession per Signed In User

### Actual result
There are tons of UserSessions per Signed In User

### Technical information
This is from the code on the EcoSystem Branch

##### Involved apps' version
This is being done using the mapped versions of these apps.  Checkout
Starcounter/SignIn.Mapper
Starcounter/UserAdmin.Mapper

Build environment from there

*This has the potential to create some serious performance issues, so it would be good to deal with this sooner rather than later.

**Comment by Mihaiii** [comment]
This was discussed before on github.
@habib535 can provide more details.

**Comment by habib535** [comment]
There was a similar bug logged https://github.com/Starcounter/AppsTeam/issues/264. This is how Starcounter sessions are designed, Sessions are separate for each tab of the browser and once you refresh the page you get new. In the Flexovital project, we have a scheduler that removes all expired sessions from database overnight, I'll merge those changes in your branch.

**Comment by wanderlust-ginge** [comment]
Cool.  Thanks for the clarification!

**Comment by Mihaiii** [comment]
Closing as answered.
